-- ════════════════════════════════════════════════════════════════
-- REFERRAL LINKS
-- Run AFTER affiliates.sql and the products setup. Safe to re-run.
-- Public link format: /r/<code>  ->  redirects to /products/<product_id>
-- ════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════
-- SECTION 1: referral_links table
-- One row per generated link. Deleting a link is a SOFT delete
-- (status = 'deleted'): visits and orders recorded later against the
-- link id stay correct, and the code can never be reused or hijacked.
-- ════════════════════════════════════════════════════════════════
create table if not exists public.referral_links (
  id            uuid primary key default gen_random_uuid(),

  -- RESTRICT: affiliates are only ever soft-deleted, so history stays.
  affiliate_id  uuid not null references public.affiliates(id) on delete restrict,

  -- If the admin removes a product entirely, its links go with it.
  product_id    uuid not null references public.products(id) on delete cascade,

  -- Random 8-character code, generated by the server. Unique across ALL
  -- rows, deleted ones included, so an old code is never handed out again.
  code          text not null unique
                  check (code ~ '^[A-Z0-9]{8}$'),

  status        text not null default 'active'
                  check (status in ('active', 'deleted')),
  deleted_at    timestamptz,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists referral_links_affiliate_idx
  on public.referral_links (affiliate_id, created_at desc);
create index if not exists referral_links_product_idx
  on public.referral_links (product_id);

-- ONE live link per affiliate per product. To get a fresh link for the
-- same product, delete the old one first, then generate again.
create unique index if not exists referral_links_one_active_per_product
  on public.referral_links (affiliate_id, product_id)
  where status = 'active';

drop trigger if exists referral_links_touch_updated_at on public.referral_links;
create trigger referral_links_touch_updated_at
  before update on public.referral_links
  for each row execute function public.touch_updated_at();


-- ════════════════════════════════════════════════════════════════
-- SECTION 2: column guard
-- RLS cannot restrict individual columns, so a trigger does it. A
-- non-admin may do exactly one thing to a link: active -> deleted.
-- They cannot re-activate it, change its code, move it to another
-- product, or hand it to another affiliate.
-- ════════════════════════════════════════════════════════════════
create or replace function public.protect_referral_link_fields()
returns trigger
language plpgsql
as $$
begin
  if public.is_admin() then
    if new.status = 'deleted' and old.status <> 'deleted' then
      new.deleted_at := coalesce(new.deleted_at, now());
    end if;
    return new;
  end if;

  if new.affiliate_id is distinct from old.affiliate_id
     or new.product_id is distinct from old.product_id
     or new.code       is distinct from old.code
     or new.created_at is distinct from old.created_at
  then
    raise exception 'Referral link details cannot be changed';
  end if;

  if new.status is distinct from old.status then
    if not (old.status = 'active' and new.status = 'deleted') then
      raise exception 'A deleted referral link cannot be restored';
    end if;
    new.deleted_at := now();
  elsif new.deleted_at is distinct from old.deleted_at then
    raise exception 'Referral link details cannot be changed';
  end if;

  return new;
end;
$$;

drop trigger if exists referral_links_protect_fields on public.referral_links;
create trigger referral_links_protect_fields
  before update on public.referral_links
  for each row execute function public.protect_referral_link_fields();


-- ════════════════════════════════════════════════════════════════
-- SECTION 3: Row Level Security
-- Admin: full access.
-- Affiliate: read their own links, create links for themselves (only
--            while active, only for active products), and soft-delete
--            their own (the Section 2 trigger limits updates to that).
--            No hard delete.
-- Everyone else, including stockists and anonymous visitors: nothing.
-- Visitors never read this table directly; they go through the
-- resolve_referral_link() function in Section 4.
-- ════════════════════════════════════════════════════════════════
alter table public.referral_links enable row level security;

drop policy if exists "admin manages referral links" on public.referral_links;
create policy "admin manages referral links"
  on public.referral_links for all
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "affiliate reads own links" on public.referral_links;
create policy "affiliate reads own links"
  on public.referral_links for select
  using (
    public.is_affiliate()
    and affiliate_id = public.current_affiliate_id()
  );

drop policy if exists "affiliate creates own links" on public.referral_links;
create policy "affiliate creates own links"
  on public.referral_links for insert
  with check (
    public.is_affiliate()
    and affiliate_id = public.current_affiliate_id()
    and status = 'active'
    and exists (
      select 1 from public.affiliates a
      where a.id = affiliate_id and a.status = 'active'
    )
    and exists (
      select 1 from public.products p
      where p.id = product_id and p.status = 'active'
    )
  );

drop policy if exists "affiliate deletes own links" on public.referral_links;
create policy "affiliate deletes own links"
  on public.referral_links for update
  using (
    public.is_affiliate()
    and affiliate_id = public.current_affiliate_id()
  )
  with check (
    public.is_affiliate()
    and affiliate_id = public.current_affiliate_id()
  );


-- ════════════════════════════════════════════════════════════════
-- SECTION 4: public resolver for /r/<code>
-- Anonymous visitors cannot read referral_links (RLS), so the redirect
-- route calls this function instead. It runs with the owner's rights
-- but returns a row ONLY when the whole chain is valid: link active,
-- affiliate active, product active. Otherwise it returns nothing and
-- the route sends the visitor to the normal shop.
-- It exposes only ids, never the affiliate's name, email or bank data.
-- ════════════════════════════════════════════════════════════════
create or replace function public.resolve_referral_link(p_code text)
returns table (link_id uuid, product_id uuid, affiliate_id uuid)
language sql
stable
security definer
set search_path = public
as $$
  select l.id, l.product_id, l.affiliate_id
  from public.referral_links l
  join public.affiliates a on a.id = l.affiliate_id
  join public.products   p on p.id = l.product_id
  where l.code = upper(p_code)
    and l.status = 'active'
    and a.status = 'active'
    and p.status = 'active'
  limit 1;
$$;

revoke all on function public.resolve_referral_link(text) from public;
grant execute on function public.resolve_referral_link(text) to anon, authenticated;



-- ════════════════════════════════════════════════════════════════
-- REFERRAL FIX
-- Run AFTER affiliates.sql, affiliates-commission-bank.sql and
-- referral-links.sql. Safe to re-run.
--
-- Fixes:
--   1. Affiliates had no referral_code, so the finasto_ref cookie never
--      matched anyone and every order was saved as "Direct".
--   2. Checkout runs as an anonymous visitor, and RLS hides the affiliates
--      table from them, so the attribution lookup always came back empty.
--      A public resolver function (ids and rates only) replaces it.
--   3. A guest could not add order_items, because the policy checked the
--      order through a read the guest is not allowed to make.
-- ════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════
-- SECTION 1: affiliates.referral_code
-- One short code per affiliate, generated by the database, used in the
-- finasto_ref cookie (from /r/<code> links AND the old ?ref= links).
-- ════════════════════════════════════════════════════════════════
alter table public.affiliates
  add column if not exists referral_code text;

create or replace function public.generate_affiliate_referral_code()
returns text
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_code text;
begin
  loop
    v_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
    exit when not exists (
      select 1 from public.affiliates where referral_code = v_code
    );
  end loop;
  return v_code;
end;
$$;

-- Give every existing affiliate a code.
update public.affiliates
set referral_code = public.generate_affiliate_referral_code()
where referral_code is null;

alter table public.affiliates
  alter column referral_code set not null;

create unique index if not exists affiliates_referral_code_key
  on public.affiliates (referral_code);

-- New affiliates get a code automatically (the admin form never types one).
create or replace function public.set_affiliate_referral_code()
returns trigger
language plpgsql
as $$
begin
  if new.referral_code is null or new.referral_code = '' then
    new.referral_code := public.generate_affiliate_referral_code();
  end if;
  return new;
end;
$$;

drop trigger if exists affiliates_set_referral_code on public.affiliates;
create trigger affiliates_set_referral_code
  before insert on public.affiliates
  for each row execute function public.set_affiliate_referral_code();


-- ════════════════════════════════════════════════════════════════
-- SECTION 2: column guard (replaces the function from the
-- commission/bank migration). Adds referral_code, so an affiliate can
-- never change their own code.
-- ════════════════════════════════════════════════════════════════
create or replace function public.protect_affiliate_admin_fields()
returns trigger
language plpgsql
as $$
begin
  if public.is_admin() then
    return new;
  end if;

  if new.status             is distinct from old.status
     or new.stockist_id        is distinct from old.stockist_id
     or new.email              is distinct from old.email
     or new.profile_id         is distinct from old.profile_id
     or new.notes              is distinct from old.notes
     or new.commission_percent is distinct from old.commission_percent
     or new.referral_code      is distinct from old.referral_code
  then
    raise exception 'Only an admin can change affiliate status, stockist, email, notes, commission rate or referral code';
  end if;

  return new;
end;
$$;


-- ════════════════════════════════════════════════════════════════
-- SECTION 3: /r/<code> resolver now also returns the affiliate's
-- referral_code (the value the route stores in the cookie).
-- The return type changes, so the old function is dropped first.
-- ════════════════════════════════════════════════════════════════
drop function if exists public.resolve_referral_link(text);

create function public.resolve_referral_link(p_code text)
returns table (
  link_id uuid,
  product_id uuid,
  affiliate_id uuid,
  referral_code text
)
language sql
stable
security definer
set search_path = public
as $$
  select l.id, l.product_id, l.affiliate_id, a.referral_code
  from public.referral_links l
  join public.affiliates a on a.id = l.affiliate_id
  join public.products   p on p.id = l.product_id
  where l.code = upper(p_code)
    and l.status = 'active'
    and a.status = 'active'
    and p.status = 'active'
  limit 1;
$$;

revoke all on function public.resolve_referral_link(text) from public;
grant execute on function public.resolve_referral_link(text) to anon, authenticated;


-- ════════════════════════════════════════════════════════════════
-- SECTION 4: checkout attribution resolver
-- Called by checkout (anonymous visitors included). Returns the
-- affiliate and their CURRENT active stockist for a referral code, only
-- when the affiliate is active and has a login. It exposes ids and
-- rates only, never email, phone or bank data.
-- profile ids are what orders.affiliate_id / orders.stockist_id
-- reference (profiles.id = auth user id).
-- ════════════════════════════════════════════════════════════════
create or replace function public.resolve_referral_attribution(p_code text)
returns table (
  affiliate_id uuid,
  affiliate_profile_id uuid,
  affiliate_name text,
  commission_percent numeric,
  stockist_id uuid,
  stockist_profile_id uuid,
  stockist_profit_percent numeric
)
language sql
stable
security definer
set search_path = public
as $$
  select
    a.id,
    a.profile_id,
    a.name,
    a.commission_percent,
    s.id,
    s.profile_id,
    s.default_profit_percent
  from public.affiliates a
  left join public.stockists s
    on s.id = a.stockist_id and s.status = 'active'
  where a.referral_code = upper(trim(p_code))
    and a.status = 'active'
    and a.profile_id is not null
  limit 1;
$$;

revoke all on function public.resolve_referral_attribution(text) from public;
grant execute on function public.resolve_referral_attribution(text) to anon, authenticated;


-- ════════════════════════════════════════════════════════════════
-- SECTION 5: let guests add items to their own pending order
-- The old policy looked the order up directly, but a guest cannot read
-- orders, so the check always failed for them. This helper checks it
-- with the owner's rights instead. Still limited to pending orders, and
-- order ids are random UUIDs that cannot be guessed.
-- ════════════════════════════════════════════════════════════════
create or replace function public.is_pending_order(p_order_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.orders o
    where o.id = p_order_id and o.payment_status = 'pending'
  );
$$;

revoke all on function public.is_pending_order(uuid) from public;
grant execute on function public.is_pending_order(uuid) to anon, authenticated;

drop policy if exists "guest creates items on pending order" on public.order_items;
create policy "guest creates items on pending order"
  on public.order_items for insert
  with check (public.is_pending_order(order_id));